/**
 * WarpXSwap InfoPool Crank
 *
 * Runs the 4-step per-asset, per-slot cycle:
 *   1. update_pyth_feeds       — read Pyth V2, update EMAs + confidence
 *   2. push_oracle_price_to_pool — CPI → Pool.AssetAccount.oracle_price
 *   3. run_threshold_check     — 3-layer evaluation, may block/unblock
 *   4. calculate_and_push_fee  — V-shape fee (or static for stables), CPI → Pool
 *
 * Volume push (push_volume) runs at lower cadence (~60s) via DexScreener.
 *
 * Setup:
 *   1. Copy .env.example to .env and fill in your values
 *   2. Run: npm run dev  (ts-node)
 *   3. Or build + run: npm run build && npm start
 */

import "dotenv/config";
import { PublicKey } from "@solana/web3.js";
import { AnchorProvider, Program, Wallet } from "@coral-xyz/anchor";
import { loadConfig }       from "./config";
import { logger, setLogLevel } from "./logger";
import { startCrankLoop, PoolConfig } from "./loop";

// ── IDL imports (generated by `anchor build`) ─────────────────
// These paths are relative to the Anchor workspace root.
// Run `anchor build` first to generate target/types/*.ts
import type { IdlTypes } from "@coral-xyz/anchor";

async function main(): Promise<void> {
  const cfg = loadConfig();
  setLogLevel(cfg.logLevel);

  const wallet   = new Wallet(cfg.crankKeypair);
  const provider = new AnchorProvider(cfg.connection, wallet, {
    commitment: "confirmed",
    skipPreflight: false,
  });

  // Load IDLs — generated by `anchor build`
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  let infoPoolIdl: unknown;
  try {
    infoPoolIdl = require("../../target/idl/info_pool_program.json");
  } catch {
    logger.error("main", "IDL not found — run `anchor build` first");
    process.exit(1);
  }

  const infoPoolProgram = new Program(
    infoPoolIdl as Parameters<typeof Program>[0],
    provider,
  );

  const poolProgramId = new PublicKey(cfg.poolProgramId);

  // ── Configure which pools and assets this crank watches ──────
  // Replace these with your actual deployed pool owners and Pyth feed accounts.
  // Each pool can have multiple assets.
  //
  // Pyth V2 price accounts on devnet:
  //   SOL/USD:  H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG
  //   BTC/USD:  GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU
  //   ETH/USD:  JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB
  //   USDC/USD: Dpw1EAVrSB1ibxiDQyTAW6Zip3J4Btez2ssa5GR3vTVE

  const pools: PoolConfig[] = [
    // EXAMPLE — replace with real values after anchor deploy
    // {
    //   poolOwner: new PublicKey("YOUR_POOL_AUTHORITY_PUBKEY"),
    //   assets: [
    //     {
    //       mint:            new PublicKey("So11111111111111111111111111111111111111112"), // wSOL
    //       mintAddr:        "So11111111111111111111111111111111111111112",
    //       pythPriceAccount: new PublicKey("H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"),
    //     },
    //   ],
    // },
  ];

  // Load pool config from env if provided
  const poolsEnv = process.env["POOL_CONFIGS"];
  if (poolsEnv) {
    try {
      const parsed = JSON.parse(poolsEnv) as Array<{
        poolOwner: string;
        assets: Array<{
          mint: string;
          mintAddr: string;
          pythPriceAccount: string;
        }>;
      }>;
      for (const p of parsed) {
        pools.push({
          poolOwner: new PublicKey(p.poolOwner),
          assets: p.assets.map(a => ({
            mint:             new PublicKey(a.mint),
            mintAddr:         a.mintAddr,
            pythPriceAccount: new PublicKey(a.pythPriceAccount),
          })),
        });
      }
      logger.info("main", `Loaded ${pools.length} pool(s) from POOL_CONFIGS env`);
    } catch (err) {
      logger.error("main", "Failed to parse POOL_CONFIGS env var", err);
      process.exit(1);
    }
  }

  if (pools.length === 0) {
    logger.warn("main", "No pools configured — crank will idle. Set POOL_CONFIGS env var.");
    logger.warn("main", "See POOL_CONFIGS format in crank/README.md");
  }

  // Handle graceful shutdown
  process.on("SIGINT",  () => { logger.info("main", "SIGINT — shutting down"); process.exit(0); });
  process.on("SIGTERM", () => { logger.info("main", "SIGTERM — shutting down"); process.exit(0); });

  await startCrankLoop(infoPoolProgram, poolProgramId, pools, cfg);
}

main().catch(err => {
  console.error("[crank] Fatal error:", err);
  process.exit(1);
});
