import * as fs from "fs";
import * as path from "path";
import { AnchorProvider, Program } from "@coral-xyz/anchor";

// IDL filenames generated by `anchor build`
const IDL_NAMES = {
  pool:       "pool_program",
  infoPool:   "info_pool_program",
  governance: "governance_program",
  routing:    "routing_program",
} as const;

// Search order:
//   1. WarpXSwap/target/idl/   — generated by `anchor build` (authoritative)
//   2. WarpXSwap/sdk/idl/      — committed copies via `pnpm sync-idl`
const IDL_SEARCH_DIRS = [
  path.resolve(__dirname, "../../target/idl"),
  path.resolve(__dirname, "../idl"),
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function loadIdl(programKey: keyof typeof IDL_NAMES): any {
  const filename = `${IDL_NAMES[programKey]}.json`;
  for (const dir of IDL_SEARCH_DIRS) {
    const full = path.join(dir, filename);
    if (fs.existsSync(full)) {
      return JSON.parse(fs.readFileSync(full, "utf-8"));
    }
  }
  throw new Error(
    `IDL not found for '${programKey}' (${filename}).\n` +
    `Run 'anchor build' then 'pnpm --filter @warpxswap/sdk sync-idl'.`
  );
}

// ── Program factories ──────────────────────────────────────────

export function createPoolProgram(provider: AnchorProvider): Program {
  return new Program(loadIdl("pool"), provider);
}

export function createInfoPoolProgram(provider: AnchorProvider): Program {
  return new Program(loadIdl("infoPool"), provider);
}

export function createGovernanceProgram(provider: AnchorProvider): Program {
  return new Program(loadIdl("governance"), provider);
}

export function createRoutingProgram(provider: AnchorProvider): Program {
  return new Program(loadIdl("routing"), provider);
}

// ── All-in-one factory ─────────────────────────────────────────
// Returns all four programs in one call.
//
// Usage:
//   const { pool, infoPool, governance, routing } = createPrograms(provider);
//   const client = new GovernanceClient(governance, poolOwner);

export interface WarpXPrograms {
  pool:       Program;
  infoPool:   Program;
  governance: Program;
  routing:    Program;
}

export function createPrograms(provider: AnchorProvider): WarpXPrograms {
  return {
    pool:       createPoolProgram(provider),
    infoPool:   createInfoPoolProgram(provider),
    governance: createGovernanceProgram(provider),
    routing:    createRoutingProgram(provider),
  };
}

// ── IDL path inspector (for debugging) ────────────────────────
// Prints where each IDL was found (or not found).
export function inspectIdlPaths(): void {
  for (const [key, filename] of Object.entries(IDL_NAMES)) {
    const full = `${filename}.json`;
    let found = "(not found — run anchor build)";
    for (const dir of IDL_SEARCH_DIRS) {
      const p = path.join(dir, full);
      if (fs.existsSync(p)) {
        found = p;
        break;
      }
    }
    console.log(`[idl] ${key.padEnd(12)} → ${found}`);
  }
}
