import { PublicKey, Keypair, SystemProgram, LAMPORTS_PER_SOL } from "@solana/web3.js";
import { BankrunProvider } from "anchor-bankrun";
import { startAnchor, ProgramTestContext, BanksClient } from "solana-bankrun";
import { Program, AnchorProvider, Wallet, BN } from "@coral-xyz/anchor";
import {
  createMint,
  createAccount,
  mintTo,
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
  createAssociatedTokenAccount,
} from "@solana/spl-token";
import { findPoolPda, findAssetPda, findLpDepositPda, findInfoPoolPda } from "../../sdk/src/pdas";

// ── Constants matching the Rust source ──────────────────────────
export const FEE_SCALE           = BigInt("1000000000"); // 1e9
export const BPS_DENOMINATOR     = BigInt("10000");
export const POOL_PROGRAM_ID_STR = "4AXtXF5VWeWKLqP6vHKPpjoc7wQ8r4duDqZ4CENtzsqZ";
export const INFO_POOL_ID_STR    = "9MXoZpzQZzvURN1S1EARJLaDhFuGw3RAppQMYvGTcmPo";

// ── Test context types ──────────────────────────────────────────
export interface TestCtx {
  context:     ProgramTestContext;
  provider:    BankrunProvider;
  program:     Program;
  authority:   Keypair;
  alice:       Keypair;
  bob:         Keypair;
  mintSol:     PublicKey;   // fake wSOL mint
  mintUsdc:    PublicKey;   // fake USDC mint
  poolPda:     PublicKey;
  solAssetPda: PublicKey;
  usdcAssetPda: PublicKey;
}

// ── Load IDL (generated by `anchor build`) ─────────────────────
export function loadPoolIdl(): unknown {
  try {
    return require("../../../target/idl/pool_program.json");
  } catch {
    throw new Error(
      "IDL not found — run `anchor build` first to generate target/idl/pool_program.json",
    );
  }
}

// ── Bankrun setup ──────────────────────────────────────────────
export async function createTestContext(): Promise<TestCtx> {
  const authority = Keypair.generate();
  const alice     = Keypair.generate();
  const bob       = Keypair.generate();

  // Start bankrun with the pool program
  const context = await startAnchor(
    ".",   // Anchor workspace root
    [],    // extra programs (info_pool, governance etc. added if needed)
    [
      // Pre-fund wallets
      { address: authority.publicKey, info: { lamports: 100 * LAMPORTS_PER_SOL, data: Buffer.alloc(0), owner: SystemProgram.programId, executable: false } },
      { address: alice.publicKey,     info: { lamports: 100 * LAMPORTS_PER_SOL, data: Buffer.alloc(0), owner: SystemProgram.programId, executable: false } },
      { address: bob.publicKey,       info: { lamports: 100 * LAMPORTS_PER_SOL, data: Buffer.alloc(0), owner: SystemProgram.programId, executable: false } },
    ],
  );

  const provider = new BankrunProvider(context);
  const idl      = loadPoolIdl();
  const program  = new Program(idl as Parameters<typeof Program>[0], provider);

  const banksClient = context.banksClient;

  // Create test token mints
  const mintSol  = await createTestMint(context, authority, 9);  // 9 decimals like wSOL
  const mintUsdc = await createTestMint(context, authority, 6);  // 6 decimals like USDC

  const [poolPda]      = findPoolPda(authority.publicKey);
  const [solAssetPda]  = findAssetPda(poolPda, mintSol);
  const [usdcAssetPda] = findAssetPda(poolPda, mintUsdc);

  return {
    context, provider, program, authority, alice, bob,
    mintSol, mintUsdc, poolPda, solAssetPda, usdcAssetPda,
  };
}

// ── Token helpers ──────────────────────────────────────────────

// ── Real bankrun SPL token helpers (Bug #20 fix) ───────────────
// The previous implementations were stubs: createTestMint returned a
// random keypair without creating the mint on-chain, and mintTokens
// had an empty body.  Both are now wired to the fully-implemented
// helpers in tests/helpers/mint.ts.

export async function createTestMint(
  context:   ProgramTestContext,
  authority: Keypair,
  decimals:  number,
): Promise<PublicKey> {
  const { createMintBankrun } = await import("./mint");
  return createMintBankrun(context, authority, decimals);
}

export async function mintTokens(
  context:     ProgramTestContext,
  mint:        PublicKey,
  destination: PublicKey,
  amount:      bigint,
  authority:   Keypair,
): Promise<void> {
  const { mintTokensBankrun } = await import("./mint");
  await mintTokensBankrun(context, mint, destination, amount, authority);
}

export async function getTokenBalance(
  context: ProgramTestContext,
  account: PublicKey,
): Promise<bigint> {
  const info = await context.banksClient.getAccount(account);
  if (!info) return 0n;
  // Parse SPL token account data (bytes 64-72 = amount u64 LE)
  const data = Buffer.from(info.data);
  if (data.length < 72) return 0n;
  return data.readBigUInt64LE(64);
}

// ── Pool-wide fee math helpers (mirror on-chain formula) ────────

// Bug #2 constants
export const ORACLE_PRICE_SCALE      = BigInt("1000000"); // 1e6
export const MAX_ORACLE_STALENESS_SLOTS = 150n;

/**
 * Compute pool_fps increment for a single swap (pre-Bug-#2, native units).
 *   Δfps = out_fee_amount × FEE_SCALE / pool_total_lp_deposited
 * NOTE: this is the BUGGY formula — kept for regression comparison in tests.
 */
export function computeFpsIncrement(
  outFeeAmount:         bigint,
  poolTotalLpDeposited: bigint,
): bigint {
  if (poolTotalLpDeposited === 0n) return 0n;
  return (outFeeAmount * FEE_SCALE) / poolTotalLpDeposited;
}

/**
 * USD-normalise a deposit amount (Bug #2 fix).
 *   amount_usd = amount × oracle_price / (ORACLE_PRICE_SCALE × 10^decimals)
 *
 * oracle_price encodes USD per whole token × ORACLE_PRICE_SCALE (1e6).
 *   e.g. SOL at $150 → oracle_price = 150_000_000
 *
 * If oracle_price = 0 (pre-first-price-push), falls back to native amount.
 */
export function computeAmountUsd(
  amount:      bigint,
  oraclePrice: bigint,
  decimals:    number,
): bigint {
  if (oraclePrice === 0n) return amount; // fallback: no oracle yet
  const tokenScale = 10n ** BigInt(decimals);
  return (amount * oraclePrice) / (ORACLE_PRICE_SCALE * tokenScale);
}

/**
 * USD-normalise an outgoing swap fee (Bug #2 fix, mirrors swap.rs step 10).
 *   fee_usd = out_fee_amount × oracle_price_out
 *             / (ORACLE_PRICE_SCALE × 10^decimals_out)
 */
export function computeFeeUsd(
  outFeeAmount:  bigint,
  oraclePriceOut: bigint,
  decimalsOut:    number,
): bigint {
  const tokenScale = 10n ** BigInt(decimalsOut);
  return (outFeeAmount * oraclePriceOut) / (ORACLE_PRICE_SCALE * tokenScale);
}

/**
 * USD-normalised pool_fps increment (Bug #2 fix).
 *   fps_inc = fee_usd × FEE_SCALE / pool_total_lp_deposited_usd
 */
export function computeFpsIncrementUsd(
  feeUsd:                   bigint,
  poolTotalLpDepositedUsd:  bigint,
): bigint {
  if (poolTotalLpDepositedUsd === 0n) return 0n;
  return (feeUsd * FEE_SCALE) / poolTotalLpDepositedUsd;
}

/**
 * LP's claimable fees in USD units (Bug #2 fix, mirrors handler_public_exit).
 *   claimable_usd = pending_fees_usd
 *                 + amount_usd × (pool_fps − fee_debt) / FEE_SCALE
 */
export function computeClaimableUsd(
  amountUsd:      bigint,
  poolFps:        bigint,
  feeDebt:        bigint,
  pendingFeesUsd: bigint,
): bigint {
  const fpsDelta    = poolFps > feeDebt ? poolFps - feeDebt : 0n;
  const accrued     = (amountUsd * fpsDelta) / FEE_SCALE;
  return pendingFeesUsd + accrued;
}

/**
 * Convert USD-valued claimable back to native tokens at current oracle price
 * (Bug #2 fix — mirrors the native-conversion step in handler_public_exit).
 *   claimable_native = claimable_usd × ORACLE_PRICE_SCALE × 10^decimals
 *                      / oracle_price
 *
 * Returns 0 if oracle_price = 0 (no price pushed yet — no fees to claim).
 */
export function computeClaimableNative(
  claimableUsd: bigint,
  oraclePrice:  bigint,
  decimals:     number,
): bigint {
  if (oraclePrice === 0n || claimableUsd === 0n) return 0n;
  const tokenScale = 10n ** BigInt(decimals);
  return (claimableUsd * ORACLE_PRICE_SCALE * tokenScale) / oraclePrice;
}

/**
 * Compute LP's claimable fees (original native-unit formula).
 *   claimable = pending_fees + amount × (pool_fps − fee_debt) / FEE_SCALE
 */
export function computeClaimable(
  lpAmount:    bigint,
  poolFps:     bigint,
  feeDebt:     bigint,
  pendingFees: bigint,
): bigint {
  const fpsDelta    = poolFps > feeDebt ? poolFps - feeDebt : 0n;
  const fullAccrued = (lpAmount * fpsDelta) / FEE_SCALE;
  return pendingFees + fullAccrued;
}

/**
 * Compute swap out_fee_amount.
 *   out_fee_amount = amount_out_before_fee × current_fee_bps / BPS_DENOMINATOR
 */
export function computeOutFee(amountOutBeforeFee: bigint, feeBps: bigint): bigint {
  return (amountOutBeforeFee * feeBps) / BPS_DENOMINATOR;
}

/**
 * Expected pool_fps after N swaps each contributing outFeeAmount.
 */
export function expectedPoolFpsAfterSwaps(
  swaps:                Array<{ outFeeAmount: bigint }>,
  poolTotalLpDeposited: bigint,
): bigint {
  return swaps.reduce((fps, s) => fps + computeFpsIncrement(s.outFeeAmount, poolTotalLpDeposited), 0n);
}

/**
 * Staleness check mirroring swap.rs Bug #3 guard.
 * Returns true if the price is fresh enough to accept the swap.
 *   fresh = oracle_price_slot > 0
 *           && current_slot - oracle_price_slot <= MAX_ORACLE_STALENESS_SLOTS
 */
export function isOracleFresh(oraclePriceSlot: bigint, currentSlot: bigint): boolean {
  if (oraclePriceSlot === 0n) return false; // never pushed
  return (currentSlot - oraclePriceSlot) <= MAX_ORACLE_STALENESS_SLOTS;
}
